### model
model_name_or_path: LLaMA-Factory/pretrained/gemma-3-4b-it
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # 3

### dataset
dataset: GraSP_60s # video: mllm_video_demo
template: gemma3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
save_strategy: steps
output_dir: LLaMA-Factory/saves/gemma-3-4b-it_60s/lora/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
save_total_limit: 2
### train
per_device_train_batch_size: 12
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
